# Generated by Django 4.2.23 on 2025-08-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secureuser',
            name='login_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
