# Generated by Django 4.2.23 on 2025-09-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_passwordhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="secureuser",
            name="login_attempts_reset_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
